from fastapi import FastAPI, Body
#This is the library FastAPI recommends to have to have an option query parameter
from typing import Optional
from pydantic import BaseModel
import classifier_model
from datetime import datetime

#sql alchemy to make edits to the database
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session

#Connecting to spamshiled via connection string
engine = create_engine("postgresql://postgres:postgreSQL%40123@localhost:5433/spamshield", echo=True)
connection = engine.connect()

#Making sure the input is a string
class SingleMessage(BaseModel):
    message: str
    #device_id will be generated by the android app on first launch, unique to each device
    device_id: str

#Making sure the input is an array of strings
class BulkMessages(BaseModel):
    messages: list[str]
    device_id: str

#For reporting misclassified messages
class FeedbackMessage(BaseModel):
    prediction_id: int
    actual: str


app = FastAPI()

#HTTP endpoint to make a single prediction
@app.post("/predict")
def predict_one(message:SingleMessage = Body(description="Single message as input into the model. Prediction will be ham or spam. Useful for new incoming messages")):
    data = classifier_model.predict_one(message.message)
    prediction = data["Classification"]
    score = data["Confidence"]
    #Not using formatted strings to prevent sql injections (protection against malicious input)
    connection.execute(text(""" 
    INSERT INTO prediction(message, device_id, confidence, classification) 
    VALUES(:message, :device_id, :confidence, :classification)"""), {
        "message": message.message,
        "device_id": message.device_id,
        "confidence": score,
        "classification": prediction
    })
    connection.commit()

    current_time = connection.execute(text('SELECT "timestamp" FROM prediction WHERE device_id = :device_id'), {"device_id": message.device_id})
    #obtains the first row returned
    row = current_time.first()
    #Gets the timestamp column
    timestamp = row.timestamp
    return {
        "Classification" : prediction,
        "Confidence": score,
        "Time": timestamp
    }
    #This will also return an HTTP exception automatically from the classifier_model.py script

#HTTP endpoint to make a bulk prediction -> This is only done once
@app.post("/predict-multiple")
def predict_multiple(messages:BulkMessages = Body(description="Multiple messages as an array input into the model. Predictions will be ham or spam, returned in the same order of messages. Useful for predicting previous messages")):
    #Same logic as predict_one but just in a loop. Instead of calling predict_one endpoint multiple times, 
    #just call the predict_one function in the classifier model multiple times through just one API call.
    #This call will ONLY be made when the app is installed for the first time, and that's it. 
    results = []
    current_time = datetime.now()
    for message in messages.messages:
        result = classifier_model.predict_one(message)
        #Adding current time since it wasn't natively returned
        result["Time"] = current_time
        results.append(result)
        connection.execute(text(""" 
        INSERT INTO prediction(message, device_id, confidence, classification) 
        VALUES(:message, :device_id, :confidence, :classification)"""), {
            "message": message,
            "device_id": messages.device_id,
            "confidence": result["confidence"],
            "classification": result["label"]
        })
        connection.commit()
    

    return {"Batch Predictions": results}

    #This will also return an HTTP exception automatically from the classifier_model.py script


#Just to see if the server is up and running
@app.get("/health")
def health():
    return {"status": "ok", "model_loaded": classifier_model.data is not None}

#A feedback endpoint: users report misclassified predictions here, associated with the device 
@app.post("/feedback")
def give_feedback(feedback: FeedbackMessage):
    connection.execute((text("""
    INSERT INTO feedback(prediction_id, actual) VALUES(:prediction_id, :actual)""")), {
        "prediction_id": feedback.prediction_id,
        "actual": feedback.actual
    })
    connection.commit()
    return {"Feedback": "Feedback received, we apologise for the inconvenience"}